# SwiftLint configuration – strict mode
# https://realm.github.io/SwiftLint/rule-directory.html

# ───────────────────────────── Included / Excluded ─────────────────────────────

excluded:
  - .build
  - DerivedData
  - "**/.build"

# ───────────────────────────── Disabled Rules ──────────────────────────────────

disabled_rules:
  - todo # Allow TODO/FIXME comments during development
  - trailing_comma # Style preference – we allow trailing commas

# ───────────────────────────── Opt-in Rules ────────────────────────────────────

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# ───────────────────────────── Rule Configuration ──────────────────────────────

# Force rules – treated as errors, not warnings.
force_cast: error
force_try: error
force_unwrapping:
  severity: error
implicitly_unwrapped_optional:
  severity: error

# Line length
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: false
  ignores_interpolated_strings: true

# Type body length – slightly relaxed for TCA reducers
type_body_length:
  warning: 300
  error: 500

# Function body length – slightly relaxed for TCA reducer bodies
function_body_length:
  warning: 60
  error: 120

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Nesting
nesting:
  type_level:
    warning: 2
    error: 4
  function_level:
    warning: 3
    error: 5

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 70
  excluded:
    - id
    - x
    - y
    - i
    - ok
    - to
    - no

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Multiline arguments
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

# Enum case associated values count
enum_case_associated_values_count:
  warning: 5
  error: 7

# Modifier order – use SwiftLint default ordering
